os:
- linux
language: c
addons:
  apt:
    packages:
    - libgc-dev
    - libgmp-dev
before_install:
- date
- cd ${HOME}
- export GCC=gcc
- export CLANG=clang
- export ATSHOME=${HOME}/ATS1
- export ATSHOMERELOC=ATS-0.2.12
- export PATSHOME=${HOME}/ATS2
- export PATH=${PATH}:${PATSHOME}/bin
- export TEMPTORYBUILD=${TRAVIS_BUILD_DIR}
install:
- "${TRAVIS_BUILD_DIR}/travis-ci/install-ats1.sh 0.2.12"
- "${TRAVIS_BUILD_DIR}/travis-ci/install-ats2.sh 0.3.12"
script:
- cd ${ATSHOME}
- "./configure&&make CC=${GCC} all_ngc"
- cd ${PATSHOME}
- "./configure&&make CC=${GCC} all"
- cd $TEMPTORYBUILD
- make
deploy:
  provider: releases
  api_key:
    secure: abwiLI+WHwwEHmENB+wpdz0GYl3dD1Dk0OCSYBdZyZe91S9Y15ptB5J1LMhLkhO0iF97y8sNLGp0BTi0hAww/AKot3J7rJydR/0MUZNAn1T7KWCwXifImk0BgX9QP20ARBWW8BlkAcPBUcdncJEQjWa8UJyV3UhgF95ADRN1bMof7jRzhVTrWL/2oUBQ/buU4etGONXXFlt9PImk4aYEA/fWr/jXggHDXVjw+YkJLG00Hz7cT9C3wopJVp40B64XLz4G2mL8bIh942YH8lByhrk9TpSGWqou0Y/fLR3+/HGG6wlUZi7xatPciPRoEj1P1mNkyZQMUuDHEj+h/inVij679OI5iPSh1uzT3AWeFIscX0r72xQcl17VoIEsJHzMjqQhdJKGvTzy0+D8DbDVl8xIc8GcVN/Zdmx2PpYO5N5/ylUZa5pNrYADiohxNsIEBvztZKC2/Vx60Gd1MYQuaA5ecZS6Bf3fr8ViRF6VL/hj/o4Ol9TtVftH3UDS+eCmj2T1VByaha8Vzi4kdbhB25d43t5jm78yXc2rbp8XTzuCl+X4zc57YRRfoVD8WvkwRx6/ri1dXOo/RhBvrm/RqlqB6EtO1kHASF2uTYFtUhySjiNLMsWOKMMbljItQ6KiGiVKmGk92HzOEi3SqPn+d6bJoyiYTW7ConJN0ynKN1Q=
  file: Temptory-Upstream*.tgz
  file_glob: true
  name: Temptory-Upstream-0.0.0
  prerelease: true
  skip_cleanup: true
  on:
    repo: sparverius/Temptory-Upstream
    tags: true
