os:
- linux
language: c
addons:
  apt:
    packages:
    - libgc-dev
    - libgmp-dev
before_install:
- date
- cd ${HOME}
- export GCC=gcc
- export CLANG=clang
- export ATSHOME=${HOME}/ATS1
- export ATSHOMERELOC=ATS-0.2.12
- export PATSHOME=${HOME}/ATS2
- export PATH=${PATH}:${PATSHOME}/bin
- export TEMPTORYBUILD=${TRAVIS_BUILD_DIR}
install:
- "${TRAVIS_BUILD_DIR}/travis-ci/install-ats1.sh 0.2.12"
- "${TRAVIS_BUILD_DIR}/travis-ci/install-ats2.sh 0.3.12"
script:
- cd ${ATSHOME}
- "./configure&&make CC=${GCC} all_ngc"
- cd ${PATSHOME}
- "./configure&&make CC=${GCC} all"
- cd $TEMPTORYBUILD
- make
before_deploy:
  - git tag v0.0.0
deploy:
  provider: releases
  api_key:
    secure: PCgyN+uLU9n3hII/qFl8xsDt7JrNXzN5IIsNNUVCnuIqxROlFYxAxzSlbvLp+JdN4keCmffkIis6L0kgjvEw8DoxhaoleNfvoT1Esv1mOJdbmoYpl6R5vSM0XNuoaTP5SC+9TfS5DDH8xixD72vRwOGh83TlO05Ks7jd/U+5Wze5b1q4Htp3KDanAnmrUVbCUhz0Jx7W3oLC5qQSzH5xqJMvkNYituPpYEIrwHucOoF3BZDJksWZ3RvKYFF+n6sXmhfqHHQx0XmWLkV/S9J8YOS4mUY2eyBle6fccId6RFaoKLiW9GM7KV13xzjwx0a4fyOHZs/0PVS7xXSWD70kq6bk4M7HAgQ/fa3vTqr+YgxGo2itPWIDShofkY5IIlXGyZzt9eM9AcMsh0M1jepgjbl1MpKdXICVF0SIRQnIfi5wb7IB/rqEqfelvu/qoPRJZyAYO+do/DN7ObbiVUcTSddQZ4Jg0GmxHV52F7ea8ZFBQZvoJ8J7eXWKCN7Lt/Vj4gaoddPLJCTAYGKNKA0BnZj0hj6CAQYRVybL3RIo6Q4lbNRzoNknVi/q3yj0pj+Hq30ZoLvgnQwJczt8AlHg7DAoBw1HAN9JAx/B6PUv0cyoNRnzzncHWMLANNMyVPsbz0BKfHAXg+mVsCOP5LLDJCaBpH8FZZLLsXz/oYQSmyU=
  file_glob: true
  prerelease: true
  name: ATS-Temptory-0.0.0
  skip_cleanup: true
  file: ATS-Temptory-*.tgz
  on:
    repo: sparverius/Temptory-Release
