os:
- linux
language: c
addons:
  apt:
    packages:
    - libgc-dev
    - libgmp-dev
before_install:
- date
- cd ${HOME}
- export GCC=gcc
- export CLANG=clang
- export ATSHOME=${HOME}/ATS1
- export ATSHOMERELOC=ATS-0.2.12
- export PATSHOME=${HOME}/ATS2
- export PATH=${PATH}:${PATSHOME}/bin
- export TEMPTORYBUILD=${TRAVIS_BUILD_DIR}
install:
- "${TRAVIS_BUILD_DIR}/travis-ci/install-ats1.sh 0.2.12"
- "${TRAVIS_BUILD_DIR}/travis-ci/install-ats2.sh 0.3.12"
script:
- cd ${ATSHOME}
- "./configure&&make CC=${GCC} all_ngc"
- cd ${PATSHOME}
- "./configure&&make CC=${GCC} all"
- cd $TEMPTORYBUILD
- make
deploy:
  provider: releases
  api_key:
    secure: EmWGcC/NphCqjd75OWvJNifaDaglAgpJE4xZqsPPQ55WAHcvD+bKfq0D09s8Popth6zDlMYctaQKIE07vgFHaXizGRF3xmm2raQ+i+/7ClEAcF8R85OZlWoi/MfzzAe4AzHoj6i/EnOKWE/2EvKbFYFEei4pDo3qjdwsVAXdsqNyY7cKcOm+pj35W6KFRUG07WGz2lOuok6dFlZJN5A7wX3zQic+cLiClYfTxchxh6TBswbC5fdsFfsqufDJnpUMTRyDb7GYD3bul2Q8L+qlZd5IVqFxZ2plrk0FaIup/p9O1yIrtCDLBv3O9pTVZgzWXQQiIB3k3KamyS4+F3AKS1goXfLfsCRkVKcJRyUWqVTsh385FbLaAJiUwH5weAUwKwPI/WmS1H24k/ohPGw6uki9LETI9xUYQyM8S++QqoozotfKXHgSIHNWKSZXBuC3OdjSpQlhKyuSLAW1XRFmjc+WYozfMjSS61BhswyaKTMNfK+d3f9ElHwvkUvT7VgTpdZZtqJPh3B+1YpFSp9njQ+EO3TcJFrQ66+VGSc4Qt0nSB1huY2VD+YtBOQu7BSu20/Z2RQ58TiQfLgRuAKMKxMauCeegJl7GWGNUJzMvmeyRfJQra8pJfqNAcHRG7jumdg8RJ61kJwhPu8R6eQptB5WfgCAPnwHoXOVLRDn6xs=
  file: Temptory-Upstream*.tgz
  file_glob: true
  name: Temptory-Upstream-0.0.0
  prerelease: true
  skip_cleanup: true
  on:
    repo: sparverius/Temptory-Upstream
    tags: true
